Repository codeforjapan/StudyAtHome, pull requests merged in 2020-06, with the labels that each got.

#87 旧デザインで使用されていたコンポーネントを削除
  src/components/CommentButton.vue
  src/components/MovieButton.vue
  src/components/StudyCard.vue
  src/components/SubTextBookButton.vue
  src/components/TextBookButton.vue
Labels: Pending

#129 Vuex store は subscribe しない
  src/pages/classes/index.vue
Labels: components, vuex store

#127 汎用（モーダル）ダイアログ componentを作成
  src/components/ActionButton.vue
  src/components/BaseDialog.vue
Labels: components

#142 displayDateのVuex Store分離・名前変更とリファクタリング
  src/components/PeriodCard.vue
  src/components/PeriodCardEditable.vue
  src/layouts/classes.vue
  src/pages/classes/index.vue
  src/pages/edit/index.vue
  src/store/index.ts
  src/store/modules/app.ts
  src/store/modules/classData.ts
Labels: vuex store

#144 新Lessons形式に対応する
  src/store/modules/classData.ts
  src/types/store/classData.d.ts
Labels: Ready For Merge, vuex store

#125 ログインページの作成
  src/components/ActionButton.vue
  src/components/BottomSheetLayer.vue
  src/components/EditingScreen.vue
  src/components/SimpleBottomSheet.vue
  src/pages/account/login.vue
Labels: Waiting For Review

#113 indexページの作成
  .github/workflows/firebase-deploy-development.yml
  .github/workflows/firebase-deploy.yml
  src/layouts/default.vue
  src/pages/index.vue
Labels: Waiting For Review

#154 v-snackbar に v-model で error を渡す
  src/components/EditingScreen.vue
  src/pages/account/login.vue
  src/pages/index.vue
Labels: components

#225 詳細説明部分で英文字テキストが折り返すように修正
  src/components/ContentCard.vue
  src/pages/lesson/index.vue
Labels: Ready For Merge
